add_subdirectory(EmcMC)
add_subdirectory(EmcPlotProcesses)
add_subdirectory(EmcGeoParts)
add_subdirectory(EmcTools)
add_subdirectory(EmcClustering)
add_subdirectory(EmcClustering/ClusterProperties)
add_subdirectory(EmcReco)
add_subdirectory(Timebased/WaveformGeneration)
add_subdirectory(Timebased/WaveformFeatureExtraction)
add_subdirectory(Timebased/TimeSorting)
add_subdirectory(EmcTemplateInstantiations)
