//****************************************************************************
//*                   This file is part of PandaRoot.                        *
//*                                                                          *
//*            PandaRoot is distributed under the terms of the               *
//*              GNU General Public License (GPL) version 3,                 *
//*                 copied verbatim in the file "LICENSE".                   *
//*                                                                          *
//*  Copyright (C) 2006 - 2024 FAIR GmbH and copyright holders of PandaRoot  *
//*     The copyright holders are listed in the file "COPYRIGHTHOLDERS".     *
//*               The authors are listed in the file "AUTHORS".              *
//****************************************************************************

/* Generated by Together */

#include "PndMagnet.h"
#include "FairGeoLoader.h"
#include "FairGeoInterface.h"
#include "PndGeoMagnet.h"
#include "FairGeoRootBuilder.h"
#include "FairRuntimeDb.h"
#include "PndGeoPassivePar.h"
#include "TObjArray.h"
#include "FairRun.h"
#include "FairGeoVolume.h"
#include "FairGeoNode.h"

PndMagnet::~PndMagnet() {}
PndMagnet::PndMagnet() {}

PndMagnet::PndMagnet(const char *name, const char *Title) : FairModule(name, Title) {}

void PndMagnet::ConstructGeometry()
{

  TString fileName = GetGeometryFileName();
  if (fileName.EndsWith(".geo")) {
    ConstructASCIIGeometry();
  } else if (fileName.EndsWith(".root")) {
    ConstructRootGeometry();
  } else {
    std::cout << "Geometry format not supported " << std::endl;
  }
}

Bool_t PndMagnet::CheckIfSensitive(std::string name)
{
  // just to get rid of the warrning during run, not need this is a passive element!
  (void)name; // get rid of "unused" warning
  return kFALSE;
}

void PndMagnet::ConstructASCIIGeometry()
{
  FairGeoLoader *loader = FairGeoLoader::Instance();
  FairGeoInterface *GeoInterface = loader->getGeoInterface();
  PndGeoMagnet *MGeo = new PndGeoMagnet();
  MGeo->setGeomFile(GetGeometryFileName());
  GeoInterface->addGeoModule(MGeo);
  Bool_t rc = GeoInterface->readSet(MGeo);
  if (rc)
    MGeo->create(loader->getGeoBuilder());

  TList *volList = MGeo->getListOfVolumes();
  // store geo parameter
  FairRun *fRun = FairRun::Instance();
  FairRuntimeDb *rtdb = FairRun::Instance()->GetRuntimeDb();
  PndGeoPassivePar *par = (PndGeoPassivePar *)(rtdb->getContainer("PndGeoPassivePar"));
  TObjArray *fSensNodes = par->GetGeoSensitiveNodes();
  TObjArray *fPassNodes = par->GetGeoPassiveNodes();

  TListIter iter(volList);
  FairGeoNode *node = nullptr;
  FairGeoVolume *aVol = nullptr;

  while ((node = (FairGeoNode *)iter.Next())) {
    aVol = dynamic_cast<FairGeoVolume *>(node);
    if (node->isSensitive()) {
      fSensNodes->AddLast(aVol);
    } else {
      fPassNodes->AddLast(aVol);
    }
  }
  ProcessNodes(volList);
  par->setChanged();
  par->setInputVersion(fRun->GetRunId(), 1);
}

FairModule* PndMagnet::CloneModule() const { return new PndMagnet(*this); }

ClassImp(PndMagnet)
