################################################################################
# Copyright (C) 2014-2019 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH  #
#                                                                              #
#              This software is distributed under the terms of the             #
#              GNU Lesser General Public Licence (LGPL) version 3,             #
#                  copied verbatim in the file "LICENSE"                       #
################################################################################

add_subdirectory (field)
add_subdirectory (tools)
add_subdirectory (pnddata)
add_subdirectory (detectors/drc)
add_subdirectory (detectors/dsk)
add_subdirectory (detectors/emc)
add_subdirectory (detectors/ftof)
add_subdirectory (detectors/fts)
add_subdirectory (detectors/gem)
add_subdirectory (detectors/mdt)
add_subdirectory (detectors/mvd)
add_subdirectory (detectors/passive)
#add_subdirectory (detectors/rich)
#add_subdirectory (detectors/scitil)
add_subdirectory (detectors/sds)
add_subdirectory (detectors/stt)
add_subdirectory (detectors/stt2)
